services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  nginx:
    image: 'nginx'
    volumes:
      - './frontend/dist:/usr/share/nginx/html:ro'
      - './nginx:/etc/nginx/conf.d:ro'
    ports:
      - "80:80"
